name: Build Kernel Mi6-10
on:
  push:
    branches:    
      - demon

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Init Repo
      run: |
        cd ~
        git clone https://github.com/Mech-Author/sagit-10 -b demon --depth=1 
    - name: Build With Shell
      run: |
        cd ~/sagit-10
        bash build_full.sh
    - name: Package With AnyKernel
      run: |
        cd ~
        cp sagit-10/AnyKernel ./ -r
        cd AnyKernel/
        cp ../sagit-10/out/arch/arm64/boot/Image.gz-dtb  ./
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: Mi6-10.zip
        path: /home/runner/AnyKernel/
